### PR TITLE
Fixed Wave file writer writing wrong header values

### LINKED ISSUE #1280: error in the SoundFileWriterWav :: close () method
Hi,
I found an error in the SoundFileWriterWav :: close () method. 
Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * m_channelCount * 2);  <------ bug
This variable (m_sampleCount) should not be multiplied by m_channelCount.
m_sampleCount contains the number of samples saved rather than the number of samples per channel. When I write a stereo wav 44100 samplerate this wav header has an invalid length of chunks.

To fix this:
Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * 2);  <------ bug fix

```c++
void SoundFileWriterWav::close()
{
  // If the file is open, finalize the header and close it
  if (m_file.is_open())
  {
    m_file.flush();

    //Update the main chunk size and data sub-chunk size
    //Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * m_channelCount * 2); <------bug
    Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * 2);  //<------ bug fix
    Uint32 mainChunkSize = dataChunkSize + 36;
    m_file.seekp(4);
    encode(m_file, mainChunkSize);
    m_file.seekp(40);
    encode(m_file, dataChunkSize);
    m_file.close();
  }
}

```

### PR DESCRIPTION
**Pull request by MarioLiebisch**
Fixes #1280.

Previously when updating the header fields, SFML assumed the number of samples written would be the number of samples per channel, which wasn't the case. Therefore for stereo files the written file length was actually twice the correct value. This fix uses the file size written as a basis, no longer counting the samples written altogether.

### CODE REVIEW

File: src/SFML/Audio/SoundFileWriterWav.cpp [hunk 1]
```diff
@@ -191,8 +188,9 @@ void SoundFileWriterWav::close()
         m_file.flush();
 
         // Update the main chunk size and data sub-chunk size
-        Uint32 dataChunkSize = static_cast<Uint32>(m_sampleCount * m_channelCount * 2);
-        Uint32 mainChunkSize = dataChunkSize + 36;
+        Uint32 fileSize = m_file.tellp();
```
Comment (LaurentGomila) [inline src/SFML/Audio/SoundFileWriterWav.cpp]: No compiler warning about type conversion here?

Comment (eXpl0it3r) [reply src/SFML/Audio/SoundFileWriterWav.cpp]: Our VS CI builds have warnings for it.

```src\SFML\Audio\SoundFileWriterWav.cpp(191) : warning C4244: 'initializing' : conversion from 'std::streamoff' to 'sf::Uint32', possible loss of data```

**Comment by tgnottingham** [comment]
Look good, but I think you can remove m_channelCount as well.

**Comment by MarioLiebisch** [comment]
You're right, didn't notice!
