### PR TITLE
Fixed SoundEffects example allocating effect processor resources based on source channel count instead of engine channel count

### LINKED ISSUE #3079: `SoundEffects.cpp` example segfaults due to channel count mismatch
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

The `SoundEffects.cpp` example segfaults on my machine, with invalid accesses at these lines. It seems like, in the first case, there is a mismatch in the size of `filters` (which is `music.getChannelCount()`) and the index `channel` (which goes up to `frameChannelCount`). 

In my machine, `music.getChannelCount() == 2` and `frameChannelCount == 8`.

```cpp
// L926
    outputFrames[channel] = *enabled ? filters[channel](input) : input;
//                                     ^~~~~~~~~~~~~~~~

// L770
    outputFrames[channel] = *enabled ? yn : xn;
//  ^~~~~~~~~~~~~~~~~~~~~
```

<details>
<summary>
Example stack trace
</summary>

```
0x00007ff652f16e3c in Reverb::ReverbFilter<float>::operator() (this=0x9f75450, input=0) at C:/OHWorkspace/SFML/examples/sound_effects/SoundEffects.cpp:1011
1011                auto output = static_cast<T>(0.7f * input + m_feedbackGain * m_buffer[m_cursor]);
(gdb) bt
#0  0x00007ff652f16e3c in Reverb::ReverbFilter<float>::operator() (this=0x9f75450, input=0) at C:/OHWorkspace/SFML/examples/sound_effects/SoundEffects.cpp:1011
#1  0x00007ff652f6fbfa in Reverb::Reverb()::{lambda(float const*, unsigned int&, float*, unsigned int&, unsigned int)#1}::operator()(float const*, unsigned int&, float*, unsigned int&, unsigned int) (this=0x9f17c30, inputFrames=0x9f100e0,
    inputFrameCount=@0x9df66a4: 128, outputFrames=0x26f08e0, outputFrameCount=@0x9df66a0: 128, frameChannelCount=8) at C:/OHWorkspace/SFML/examples/sound_effects/SoundEffects.cpp:926
#2  0x00007ff652f6550c in std::__invoke_impl<void, Reverb::Reverb()::{lambda(float const*, unsigned int&, float*, unsigned int&, unsigned int)#1}&, float const*, unsigned int&, float*, unsigned int&, unsigned int>(std::__invoke_other, Reverb::Reverb()::{lambda(float const*, unsigned int&, float*, unsigned int&, unsigned int)#1}&, float const*&&, unsigned int&, float*&&, unsigned int&, unsigned int&&) (__f=..., __args=@0x9df6438: 8, __args=@0x9df6438: 8,
    __args=@0x9df6438: 8, __args=@0x9df6438: 8, __args=@0x9df6438: 8) at C:/msys64/mingw64/include/c++/14.1.0/bits/invoke.h:61
#3  0x00007ff652f61c04 in std::__invoke_r<void, Reverb::Reverb()::{lambda(float const*, unsigned int&, float*, unsigned int&, unsigned int)#1}&, float const*, unsigned int&, float*, unsigned int&, unsigned int>(Reverb::Reverb()::{lambda(float const*, unsigned int&, float*, unsigned int&, unsigned int)#1}&, float const*&&, unsigned int&, float*&&, unsigned int&, unsigned int&&) (__fn=..., __args=@0x9df6438: 8, __args=@0x9df6438: 8, __args=@0x9df6438: 8, __args=@0x9df6438: 8,
    __args=@0x9df6438: 8) at C:/msys64/mingw64/include/c++/14.1.0/bits/invoke.h:111
#4  0x00007ff652f3f4e3 in std::_Function_handler<void (float const*, unsigned int&, float*, unsigned int&, unsigned int), Reverb::Reverb()::{lambda(float const*, unsigned int&, float*, unsigned int&, unsigned int)#1}>::_M_invoke(std::_Any_data const&, float const*&&, unsigned int&, float*&&, unsigned int&, unsigned int&&) (__functor=..., __args=@0x9df6438: 8, __args=@0x9df6438: 8, __args=@0x9df6438: 8, __args=@0x9df6438: 8, __args=@0x9df6438: 8)
    at C:/msys64/mingw64/include/c++/14.1.0/bits/std_function.h:290
#5  0x00007ff652f260dc in std::function<void (float const*, unsigned int&, float*, unsigned int&, unsigned int)>::operator()(float const*, unsigned int&, float*, unsigned int&, unsigned int) const (this=0x9ec60c8, __args=8, __args=8,
    __args=8, __args=8, __args=8) at C:/msys64/mingw64/include/c++/14.1.0/bits/std_function.h:591
#6  0x00007ff652d8d38c in sf::priv::MiniaudioUtils::SoundBase::processEffect (this=0x9ec5b20, framesIn=0x9df6ec0, frameCountIn=@0x9df66a4: 128, framesOut=0x9df66d0, frameCountOut=@0x9df66a0: 128)
    at C:/OHWorkspace/SFML/src/SFML/Audio/MiniaudioUtils.cpp:219
#7  0x00007ff652d8d98c in sf::priv::MiniaudioUtils::SoundBase::initialize(void (*)(void*, ma_sound*))::$_0::operator()(void*, float const**, unsigned int*, float**, unsigned int*) const (this=0x9df6517, node=0x9ec5b80, framesIn=0x9df6ec0,
    frameCountIn=0x9df66a4, framesOut=0x9df66d0, frameCountOut=0x9df66a0) at C:/OHWorkspace/SFML/src/SFML/Audio/MiniaudioUtils.cpp:169
#8  0x00007ff652d8d930 in sf::priv::MiniaudioUtils::SoundBase::initialize(void (*)(void*, ma_sound*))::$_0::__invoke(void*, float const**, unsigned int*, float**, unsigned int*) (node=0x9ec5b80, framesIn=0x9df6ec0, frameCountIn=0x9df66a4,
    framesOut=0x9df66d0, frameCountOut=0x9df66a0) at C:/OHWorkspace/SFML/src/SFML/Audio/MiniaudioUtils.cpp:168
#9  0x00007ff652d83d82 in ma_node_process_pcm_frames_internal (pNode=0x9ec5b80, ppFramesIn=0x9df6ec0, pFrameCountIn=0x9df66a4, ppFramesOut=0x9df66d0, pFrameCountOut=0x9df66a0)
    at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:72510
#10 0x00007ff652d4c60a in ma_node_read_pcm_frames (pNode=0x9ec5b80, outputBusIndex=0, pFramesOut=0x26f08e0, frameCount=128, pFramesRead=0x9df7748, globalTime=0) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:72822
#11 0x00007ff652d84052 in ma_node_input_bus_read_pcm_frames (pInputNode=0x26ec4a0, pInputBus=0x26ec4f8, pFramesOut=0x26f08e0, frameCount=480, pFramesRead=0x9df98d0, globalTime=0)
    at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:71755
#12 0x00007ff652d4be70 in ma_node_read_pcm_frames (pNode=0x26ec4a0, outputBusIndex=0, pFramesOut=0x26f08e0, frameCount=480, pFramesRead=0x9df9988, globalTime=0) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:72632
#13 0x00007ff652d4b775 in ma_node_graph_read_pcm_frames (pNodeGraph=0x26ec338, pFramesOut=0x26f08e0, frameCount=480, pFramesRead=0x9df99f0) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:71289
#14 0x00007ff652d53ca2 in ma_engine_read_pcm_frames (pEngine=0x26ec338, pFramesOut=0x26f08e0, frameCount=480, pFramesRead=0x0) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:75264
#15 0x00007ff652cfe4c8 in sf::priv::AudioDevice::initialize()::$_0::operator()(ma_device*, void*, void const*, unsigned int) const (this=0x9df9abb, device=0x26eb640, output=0x26f08e0, frameCount=480)
    at C:/OHWorkspace/SFML/src/SFML/Audio/AudioDevice.cpp:491
#16 0x00007ff652cfe449 in sf::priv::AudioDevice::initialize()::$_0::__invoke(ma_device*, void*, void const*, unsigned int) (device=0x26eb640, output=0x26f08e0, frameCount=480) at C:/OHWorkspace/SFML/src/SFML/Audio/AudioDevice.cpp:485
#17 0x00007ff652d739ca in ma_device__on_data_inner (pDevice=0x26eb640, pFramesOut=0x26f08e0, pFramesIn=0x0, frameCount=480) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:18690
#18 0x00007ff652d73835 in ma_device__on_data (pDevice=0x26eb640, pFramesOut=0x9dfde10, pFramesIn=0x0, frameCount=96) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:18771
#19 0x00007ff652d7330e in ma_device__handle_data_callback (pDevice=0x26eb640, pFramesOut=0x9dfde10, pFramesIn=0x0, frameCount=96) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:18823
#20 0x00007ff652d0bd45 in ma_device__read_frames_from_client (pDevice=0x26eb640, frameCount=96, pFramesOut=0x9dfde10) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:18853
#21 0x00007ff652d7a7a0 in ma_device_audio_thread__default_read_write (pDevice=0x26eb640) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:19343
#22 0x00007ff652d0a032 in ma_worker_thread (pData=0x26eb640) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:40913
#23 0x00007ff652d64d5d in ma_thread_entry_proxy (pData=0x26ed000) at C:/OHWorkspace/SFML/extlibs/headers/miniaudio/miniaudio.h:16508
#24 0x00007fff73ac1fd7 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#25 0x00007fff7571b66c in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#26 0x0000000000000000 in ?? ()§
```

</details>

### Your Environment

- OS / distro / window manager: Windows 11, MinGW x64 on MSYS2
- SFML version: `master` branch
- Compiler / toolchain: clang version 18.1.6, MinGW x64 on MSYS2
- Special compiler / CMake flags: debug build mode

### Steps to reproduce

1. Clone `master`, 
2. Build 
3. Run the built example from the `examples/sound_effects` working directory

### Expected behavior

No segfault

### Actual behavior

Yes segfault

### PR DESCRIPTION
**Pull request by binary1248**
Title.

When creating miniaudio `ma_sound` objects their output bus channel count is set to the channel count of the engine they are attached to. The engine derives its channel count from the audio device. When the audio source has a lower channel count the node will automatically convert it to the engine channel count for internal processing.

This change makes sure that the effect processor buffers in the SoundEffects example are sized based on the engine channel count, which is provided via parameter, instead of the channel count of the audio source.

Without this change, if the audio device has more channels than the audio source, the code would have tried to access out-of-bounds buffers since it will use the audio source channel count to construct the buffers and the engine channel count to iterate them.

Test by running the SoundEffects example using an audio device with more than 2 output channels. On Windows this can be done without hardware using something like [VB-Audio Virtual Audio Device](https://vb-audio.com/Cable/) and setting the device channel configuration to 7.1.

Fixes #3079

### CODE REVIEW

**Review by ChrisThrasher — APPROVED** [review]

File: examples/sound_effects/SoundEffects.cpp [hunk 1]
```diff
@@ -758,12 +758,19 @@ class BiquadFilter : public Processing
...
+             state   = std::vector<State>()](const float*  inputFrames,
+                                           unsigned int& inputFrameCount,
+                                           float*        outputFrames,
+                                           unsigned int& outputFrameCount,
+                                           unsigned int  frameChannelCount) mutable
             {
+                // IMPORTANT: The channel count of the audio engine currently sourcing data from this sound
+                // will always be provided in frameChannelCount, this can be different from the channel count
+                // of the audio source so make sure to size your buffers according to the engine and not the source
+                // Ensure we have as many state objects as the audio engine has channels
```
Comment (eXpl0it3r) [inline examples/sound_effects/SoundEffects.cpp:770]: Maybe it would make sense to add this to the already length documentation of the function somehow.

**Review by eXpl0it3r — APPROVED** [review]
Tested it on my 5.1 system and it didn't crash anymore, but I couldn't hear anything in the rear speakers.

File: examples/sound_effects/SoundEffects.cpp (hunk 1 above)
Comment (binary1248) [reply examples/sound_effects/SoundEffects.cpp:770]: Added to documentation.

**Comment by binary1248** [comment]
> Tested it on my 5.1 system and it didn't crash anymore, but I couldn't hear anything in the rear speakers.

Weird... if this issue persists even with a minimal example that plays some surround sound test file open another issue and I will look into it.

**Review by eXpl0it3r — APPROVED** [review]
