### PR TITLE
EGL pixel format selection and OpenGL version parsing fixes

### LINKED ISSUE #2395: Android OpenGL context 0.0 and antialiasing
## Subject of the issue

When creating a window on Android, you get the created version 0.0 error. The app does not crash and works fully, there is just this annoying error + "Failed to activate the window's context" spam. If you also add antialiasing (which isn't supported on OpenGL ES afaik), the app also does not crash, you just get a black screen (common OpenGL stuff). Also for some reason when you set antialiasing to 1, it will say that it created version 0.0 and antialiasing x2.

image

## Your environment

Android Studio 2022.1.1 on Windows 10
SFML 2.6.x branch
Used CMake, Ninja, Android NDK 25

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode::getDesktopMode(), "App", sf::Style::Fullscreen, sf::ContextSettings(0, 0, 2));
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

It should create a valid OpenGL context.

## Actual behavior

Logs show an error +"Failed to activate the window's context" spam. With antialiasing: black screen.

### PR DESCRIPTION
**Pull request by binary1248**
We've seen that in certain situations e.g. running on certain Android platforms (#2395) or running tests on the GitHub actions VMs, the OpenGL implementation can become pretty broken and start returning values that don't follow the specification. Because failing to parse an OpenGL context version doesn't really hinder us from continuing operation if everything else works, this change just assumes a conservative version and continues instead of causing the application to terminate.

The EGL pixel format selection procedure before this change relied on `eglChooseConfig()`. Using this function to select a pixel format bears the same problems as its `wgl` and `glX` counterparts (which we don't use): The way the SFML API is designed, the user has to resort to guessing a conservative configuration to request or else it will fail and graphics becomes unusable or even causes the application to terminate (see #2395). `eglChooseConfig()` takes a set of attributes that it tries to match exactly to a pixel format available on the system. If an exact match isn't found it will just fail. The other context implementations are a bit more "user friendly" in this respect, if an exact match isn't found they will still return something that is a close enough match and emit a warning to the console if a certain attribute could not be met. This gives the user helpful feedback and allows them to adjust their requested settings based on e.g. tester feedback. This changeset makes EGL pixel format selection follow the same procedure as the other context types.

Fixes #2395
Closes #2422

### CODE REVIEW

**Review by Zombieschannel — COMMENTED** [review]
So, now that sfml 3 actually works on android, I tried this and the results are... questionable.
In normal sfml 3 I get these warnings/errors when running the app:
image

With these changes, I get the following:
image

But yeah generally, it does remove the OpenGL 0.0 error, but there still are errors.

My code for testing
```
#include <SFML/Graphics.hpp>
using namespace sf;

int main()
{
    sf::RenderWindow window;
    window.create(sf::VideoMode::getDesktopMode(), "SFML works!", sf::Style::Fullscreen);
    window.setFramerateLimit(10);
    sf::CircleShape shape(400.f);
    shape.setFillColor(sf::Color::Green);
    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::Closed)
                window.close();
            if (event.type == sf::Event::LostFocus)
                window.setActive(0);
            if (event.type == sf::Event::GainedFocus)
                window.setActive(1);
            if (event.type == sf::Event::KeyReleased)
                if (event.key.code == sf::Keyboard::Escape)
                    window.close();
        }
        if (!window.hasFocus())
            continue;
        window.clear(Color::Black);
        window.draw(shape);
        window.display();
    }
}
```

**Comment by binary1248** [comment]
That is the expected output with these changes. Because we are assuming version 1.1 if the version query fails, there is nothing for the settings check to warn about.

The context is still not being able to be set active, thus the error messages. Are you running the code in debug configuration? If you run the code in debug configuration, `eglCheck` should print additional information to the console explaining what is going wrong when trying to set the contexts active.

File: src/SFML/Window/EglContext.cpp [hunk 1]
```diff
@@ -287,67 +297,100 @@ EGLConfig EglContext::getBestConfig(EGLDisplay display, unsigned int bitsPerPixe
...
+    // Retrieve the list of available configs
+    auto configs = std::make_unique<EGLConfig[]>(static_cast<std::size_t>(configCount));
+
+    eglCheck(eglGetConfigs(display, configs.get(), configCount, &configCount));
+
+    // Evaluate all the returned configs, and pick the best one
+    int       bestScore = 0x7FFFFFFF;
+    EGLConfig bestConfig{};
+
+    for (std::size_t i = 0; i < static_cast<std::size_t>(configCount); ++i)
```
Comment (ChrisThrasher) [inline src/SFML/Window/EglContext.cpp:313]: Do we know how big this number may get? Could it ever get big enough to cause problems?

File: src/SFML/Window/EglContext.cpp [hunk 2]
```diff
@@ -287,67 +297,100 @@ EGLConfig EglContext::getBestConfig(EGLDisplay display, unsigned int bitsPerPixe
...
+        int caveat;
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_RED_SIZE, &red));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_GREEN_SIZE, &green));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_BLUE_SIZE, &blue));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_ALPHA_SIZE, &alpha));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_DEPTH_SIZE, &depth));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_STENCIL_SIZE, &stencil));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_SAMPLE_BUFFERS, &multiSampling));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_SAMPLES, &samples));
+        eglCheck(eglGetConfigAttrib(display, configs[i], EGL_CONFIG_CAVEAT, &caveat));
```
Comment (ChrisThrasher) [inline src/SFML/Window/EglContext.cpp:341]: Is it worth abstraction this `eglGetConfigAttrib` call into a lambda that we can call with the `EGL_` macro as an argument thus allowing all these local vars to be `const` and reduce code duplication or is that overkill?

```cpp
const auto getConfigAttrib = [display, configs, i](auto idkWhatVarNameToUseHere) {
    int attribute;
    eglCheck(eglGetConfigAttrib(display, configs[i], idkWhatVarNameToUseHere, &attribute));
    return attribute;
}

const int red = getConfigAttrib(EGL_RED_SIZE);
```

File: src/SFML/Window/EglContext.cpp (hunk 1 above)
Comment (binary1248) [reply src/SFML/Window/EglContext.cpp:313]: It's not that big... typically in the hundreds on a desktop system with a powerful GPU, in a mobile context probably less.

File: src/SFML/Window/EglContext.cpp (hunk 2 above)
Comment (binary1248) [reply src/SFML/Window/EglContext.cpp:341]: This code was intentionally written to be identical in structure to the code in Glx and Wgl contexts for consistency reasons. We can consider refactoring them all at the same time as you propose in a separate issue later.

**Review by ChrisThrasher — APPROVED** [review]

**Comment by binary1248** [comment]
Rebased to master.

**Review by eXpl0it3r — APPROVED** [review]
