### PR TITLE
Fixed F13-F24 and consumer key names not being returned on Windows.

### LINKED ISSUE #2872: `sf::Keyboard::getDescription` returns "Unknown" for F13+ keys on Win32
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

When calling `sf::Keyboard::getDescription` on Scancode `sf::Keyboard::Scan::F13`, and other higher function keys, the function returns "Unknown" on Win32. 

Multiple users reported this problem in my implementation, but only on Win32.

### Your Environment

- OS / distro / window manager: Win32
- SFML version: 2.6.1
- Compiler / toolchain: msbuild + vcpkg
- Special compiler / CMake flags: none

### Steps to reproduce

1. No specific steps needed aside from the code below
```cpp
#include <SFML/Graphics.hpp>
#include <SFML/Window/Event.hpp>
#include <SFML/Window/Keyboard.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();

            if (event.type == sf::Event::KeyPressed) {
                std::cout << sf::Keyboard::getDescription(sf::Keyboard::Scancode::F13).toAnsiString() << std::endl;
            }

        }

        window.clear();
        window.display();
    }
}
```

### Expected behavior

Returns a proper key description, such as "F13" or "Function key 13".

### Actual behavior

Returns "Unknown"

### PR DESCRIPTION
**Pull request by binary1248**
Title.

Fixes #2872.

Test with any keyboard that has consumer keys. For F13-F24 remap some key using [powertoys](https://learn.microsoft.com/en-us/windows/powertoys/).

### CODE REVIEW

File: src/SFML/Window/Win32/InputImpl.cpp [hunk 1]
```diff
@@ -512,6 +512,38 @@ UINT sfScanToVirtualKey(sf::Keyboard::Scancode code)
     // clang-format on
 }
 
+const char* sfScanToConsumerKeyName(sf::Keyboard::Scancode code)
```
Comment (ChrisThrasher) [inline src/SFML/Window/Win32/InputImpl.cpp:515]: Would it be more expressive to return an optional? Perhaps `std::optional<std::string_view>`? If I see an API return a `const char*` I'm not automatically going to assume it may return a null pointer.

**Comment by binary1248** [comment]
Updated.

File: src/SFML/Window/Win32/InputImpl.cpp [hunk 2]
```diff
@@ -595,10 +627,22 @@ Keyboard::Scancode delocalize(Keyboard::Key key)
 ////////////////////////////////////////////////////////////
 String getDescription(Keyboard::Scancode code)
 {
-    const WORD winCode = sfScanToWinScanExtended(code);
-    const int  bufSize = 1024;
-    WCHAR      name[bufSize];
-    const int  result = GetKeyNameText(winCode << 16, name, bufSize);
+    // Try to translate the scan code to a consumer key
+    if (const auto consumerKeyName = sfScanToConsumerKeyName(code))
+        return consumerKeyName->data();
```
Comment (ChrisThrasher) [inline src/SFML/Window/Win32/InputImpl.cpp:632]: I now see that the return value is only used here to create an `sf::String`. Would it be easier if `sfScanToConsumerKeyName` already returned an `sf::String`?

**Comment by binary1248** [comment]
Updated.

**Review by ChrisThrasher — APPROVED** [review]
