### PR TITLE
Perform sanity checks on OpenGL extensions to make sure the required entry points are actually available

### LINKED ISSUE #2462: SFML crash on Galaxy S22
## Subject of the issue

So this gets quite complicated but here is what I got.
While testing I found that for some unknown reason the SFML 2 app crashes on the Samsung galaxy S22. Since I've previously tested the same code on a dozen different devices from different manufacturers, it was quite weird. Well, it seems to crash in the window.draw() function no matter what you ask it to draw. I've tested another app that just clears the screen to a specific color and doesn't draw anything and it works without any issues.
I've captured the call stack of the crash:

image

as well as the specific line that it crashed on:

image

## My conclusion:
It seems like the galaxy S22 series has a completely new GPU compared to literally any other smartphone.
The Xclipse 920 that it has is the only Xclipse GPU ever. The now new s23 series no longer has this Xclipse GPU.
So I guess it could be a graphics driver issue. Or something similar. I haven't tried just removing this line that the program crashes on as I'm unsure what it does exactly.

## Your environment

Android Studio 2022.1.1 on Windows 10
SFML 2.6.x branch
Used CMake, Ninja, Android NDK 25

### PR DESCRIPTION
**Pull request by binary1248**
Title.

We've seen in #2814 and #2462 that some OpenGL (ES) implementations don't behave as expected and misreport extensions as being available  when they don't even provide the corresponding entry points. This change protects us from such implementations by making sure the required entry points are available in order to be able to assume that an extension is supported.

When the issue was originally reported, I had a hard time reproducing the issue, but recently I grabbed the ANGLE .dlls from a Google Chrome installation, dumped them into the binaries folder and ran the examples built using OpenGL ES, and it crashed in the same way as described in aforementioned issue. If you want to test these changes, the easiest way would be to do the same.

Closes #2814
Closes #2462

@Zombieschannel can you test this change to see if it really fixes the issue?

### CODE REVIEW

File: src/SFML/Graphics/GLExtensions.hpp [hunk 1]
```diff
@@ -41,28 +41,43 @@
 // All functionality beyond that is optional
 // and has to be checked for prior to use
 
+namespace sf::priv
+{
+// Stand-ins for desktop OpenGL feature-check flags
+// NOLINTBEGIN(readability-identifier-naming)
+extern int SF_GL_OES_multitexture;
```
Comment (ChrisThrasher) [inline src/SFML/Graphics/GLExtensions.hpp:48]: Let’s use C++17 `inline` variables to avoid the need for `extern` plus a definition in a .cpp file.

**Review by ChrisThrasher — CHANGES_REQUESTED** [review]

File: src/SFML/Graphics/GLExtensions.hpp [hunk 2]
```diff
@@ -41,28 +41,43 @@
 // All functionality beyond that is optional
 // and has to be checked for prior to use
 
+namespace sf::priv
+{
+// Stand-ins for desktop OpenGL feature-check flags
+// NOLINTBEGIN(readability-identifier-naming)
+inline int SF_GL_OES_multitexture         = 1;
```
Comment (ChrisThrasher) [inline src/SFML/Graphics/GLExtensions.hpp:48]: Where do these variables get mutated? Otherwise LGTM

**Review by ChrisThrasher — APPROVED** [review]

File: src/SFML/Graphics/GLExtensions.hpp [hunk 3]
```diff
@@ -41,28 +41,43 @@
...
+inline int SF_GL_OES_vertex_buffer_object = 1;
+// NOLINTEND(readability-identifier-naming)
+} // namespace sf::priv
+
+// Core since 1.0
+#define GLEXT_multitexture          sf::priv::SF_GL_OES_multitexture
```
Comment (vittorioromeo) [inline src/SFML/Graphics/GLExtensions.hpp:54]:
```suggestion
#define GLEXT_multitexture          ::sf::priv::SF_GL_OES_multitexture
```

I think that full qualification in macros is the clearest choice.

File: src/SFML/Graphics/GLExtensions.hpp [hunk 4]
```diff
@@ -41,28 +41,43 @@
...
+#define GLEXT_glClientActiveTexture glClientActiveTexture
+#define GLEXT_glActiveTexture       glActiveTexture
+#define GLEXT_GL_TEXTURE0           GL_TEXTURE0
+
+#define GLEXT_multitexture_dependencies sf::priv::SF_GL_OES_multitexture, glClientActiveTexture, glActiveTexture
```
Comment (vittorioromeo) [inline src/SFML/Graphics/GLExtensions.hpp:59]:
```suggestion
#define GLEXT_multitexture_dependencies ::sf::priv::SF_GL_OES_multitexture, glClientActiveTexture, glActiveTexture
```

File: src/SFML/Graphics/GLExtensions.hpp [hunk 5]
```diff
@@ -41,28 +41,43 @@
...
+#define GLEXT_GL_CLAMP_TO_EDGE   GL_CLAMP_TO_EDGE
 
 // Core since 1.1
 // 1.1 does not support GL_STREAM_DRAW so we just define it to GL_DYNAMIC_DRAW
-#define GLEXT_vertex_buffer_object true
-#define GLEXT_GL_ARRAY_BUFFER      GL_ARRAY_BUFFER
-#define GLEXT_GL_DYNAMIC_DRAW      GL_DYNAMIC_DRAW
-#define GLEXT_GL_STATIC_DRAW       GL_STATIC_DRAW
-#define GLEXT_GL_STREAM_DRAW       GL_DYNAMIC_DRAW
+#define GLEXT_vertex_buffer_object sf::priv::SF_GL_OES_vertex_buffer_object
```
Comment (vittorioromeo) [inline src/SFML/Graphics/GLExtensions.hpp:68]:
```suggestion
#define GLEXT_vertex_buffer_object ::sf::priv::SF_GL_OES_vertex_buffer_object
```

File: src/SFML/Graphics/GLExtensions.hpp [hunk 6]
```diff
@@ -41,28 +41,43 @@
...
 #define GLEXT_glBufferSubData      glBufferSubData
 #define GLEXT_glDeleteBuffers      glDeleteBuffers
 #define GLEXT_glGenBuffers         glGenBuffers
+#define GLEXT_GL_ARRAY_BUFFER      GL_ARRAY_BUFFER
+#define GLEXT_GL_DYNAMIC_DRAW      GL_DYNAMIC_DRAW
+#define GLEXT_GL_STATIC_DRAW       GL_STATIC_DRAW
+#define GLEXT_GL_STREAM_DRAW       GL_DYNAMIC_DRAW
+
+#define GLEXT_vertex_buffer_object_dependencies \
+    sf::priv::SF_GL_OES_vertex_buffer_object, glBindBuffer, glBufferData, glBufferSubData, glDeleteBuffers, glGenBuffers
```
Comment (vittorioromeo) [inline src/SFML/Graphics/GLExtensions.hpp:80]:
```suggestion
    ::sf::priv::SF_GL_OES_vertex_buffer_object, glBindBuffer, glBufferData, glBufferSubData, glDeleteBuffers, glGenBuffers
```

File: src/SFML/Graphics/GLExtensions.cpp [hunk 7]
```diff
@@ -52,6 +52,38 @@
 
 namespace sf::priv
 {
+////////////////////////////////////////////////////////////
+void extensionSanityCheck()
+{
+    static const auto check = [](int& flag, auto... entryPoints)
```
Comment (vittorioromeo) [inline src/SFML/Graphics/GLExtensions.cpp:58]: The `XXX_dependencies` macros aro only used in this file, right? Can we define them in this file rather than the `.hpp` to avoid leaking more macros? It would also make it more obvious why `entryPoints` is variadic.

**Review by vittorioromeo — CHANGES_REQUESTED** [review]

File: src/SFML/Graphics/GLExtensions.cpp (hunk 7 above)
Comment (binary1248) [reply src/SFML/Graphics/GLExtensions.cpp:58]: The idea is that they are defined right under the definition of the extension functionality so in case it has to be adjusted (add/remove functions) we would only have to make changes to 1 place (that fits on a single screen) instead of 2. Splitting them leads to a higher risk that something is accidentally left out. Also, `gl.h` already defines 1000s of macros, so us adding a handful more with carefully chosen prefixes shouldn't really matter that much.

**Review by vittorioromeo — APPROVED** [review]

**Comment by binary1248** [comment]
The code is written. Someone else can port it back to C++98 code, but that someone isn't me. 😁

**Comment by Zombieschannel** [comment]
> Would it make sense to backport this to SFML 2, since it was originally reported for it?
> 
> Also, still interested in hearing @Zombieschannel feedback on the fix

I'll test it as soon as I can, however, I don't physically have the device, my friend has it, so I'll maybe have answers in a few days but it might be longer. 😐 Sorry for the inconvenience.

**Comment by Zombieschannel** [comment]
I have good and bad news.
The crashing issue seems to have been fixed with this PR.
Unfortunately, there is still something wrong with rendering.
I tested the basic green circle example, and while it does not crash, it shows a black screen.

Did everything work normally after these changes with those Chrome dlls?

**Comment by binary1248** [comment]
I tested all the (applicable) examples myself using the Chrome ANGLE .dlls and they all worked as expected.

The changes here didn't affect any of the rendering logic at all, it stayed unchanged. The only thing that was changed is that extensions are disabled if we find out the implementation doesn't strictly follow their specifications by not providing the specified entry points.

If even less is rendered now than before, it might be a sign that there was more non-conforming stuff than we initially assumed. Like I said, the ANGLE build shipped with Chrome on Windows does not have any issues with these changes, so it might be something specific to the Samsung branch of ANGLE.

Maybe something is output to the console in debug which might help narrow down the issue. If nothing else helps you can try to step through the new code from this PR and try to find out exactly which extension is causing the issue.
