### PR TITLE
Fix crash on android when requesting the position of a touch that isn't down, and deprecate fake "realtime" touch API

### LINKED ISSUE #2257: Android nullpointer dereference when getting finger position
## Subject of the issue
When getting finger position on android the app sometimes crashes.

## Your environment
* LineageOS 18.1, also reproduced on a Pixel_2_API_R AVD (the app was built on Arch Linux)
* SFML master
* clang version 14.0.6 from android ndk r25b

## Steps to reproduce
Modify the main.cpp file in the android example to get multiple touch inputs like this:
```cpp
#include <SFML/Audio.hpp>
#include <SFML/Graphics.hpp>
#include <SFML/Graphics/Sprite.hpp>
#include <SFML/Network.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>

int main(int argc, char* argv[])
{
    sf::VideoMode screen(sf::VideoMode::getDesktopMode());

    sf::RenderWindow window(screen, "");
    window.setFramerateLimit(30);

    sf::Texture texture;
    if (!texture.loadFromFile("image.png"))
        return EXIT_FAILURE;

    sf::Sprite images[16]{
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture),
	    sf::Sprite(texture)
    };
    for(sf::Sprite image : images) {
	image.setPosition(sf::Vector2f(screen.size) / 2.f);
	image.setOrigin(sf::Vector2f(texture.getSize()) / 2.f);
    }

    sf::Font font;
    if (!font.loadFromFile("tuffy.ttf"))
        return EXIT_FAILURE;

    sf::Text text("Tap anywhere to move the logo.", font, 64);
    text.setFillColor(sf::Color::Black);
    text.setPosition({10, 10});
    bool fingers[16];

    sf::View view = window.getDefaultView();

    sf::Color background = sf::Color::White;

    // We shouldn't try drawing to the screen while in background
    // so we'll have to track that. You can do minor background
    // work, but keep battery life in mind.
    bool active = true;

    while (window.isOpen())
    {
        for (sf::Event event; active ? window.pollEvent(event) : window.waitEvent(event);)
        {
            switch (event.type)
            {
                case sf::Event::Closed:
                    window.close();
                    break;
                case sf::Event::KeyPressed:
                    if (event.key.code == sf::Keyboard::Escape)
                        window.close();
                    break;
                case sf::Event::Resized:
                    view.setSize(sf::Vector2f(event.size.width, event.size.height));
                    view.setCenter(sf::Vector2f(event.size.width, event.size.height) / 2.f);
                    window.setView(view);
                    break;
                case sf::Event::LostFocus:
                    background = sf::Color::Black;
                    break;
                case sf::Event::GainedFocus:
                    background = sf::Color::White;
                    break;

                // On Android MouseLeft/MouseEntered are (for now) triggered,
                // whenever the app loses or gains focus.
                case sf::Event::MouseLeft:
                    active = false;
                    break;
                case sf::Event::MouseEntered:
                    active = true;
                    break;
                case sf::Event::TouchBegan:
		    fingers[event.touch.finger] = true;
                    break;
                case sf::Event::TouchEnded:
		    fingers[event.touch.finger] = false;
                    break;
            }
        }

        if (active)
        {
            window.clear(background);
	    for(int i(0); i < 16; ++i)
	    {
	        if(fingers[i])
                // the issue happens with both if statements but it seems to be more rare with sf::Touch::isDown
		//if(sf::Touch::isDown(i))
                    images[i].setPosition(window.mapPixelToCoords(sf::Touch::getPosition(i, window)));
            	window.draw(images[i]);
	    }
            window.draw(text);
            window.display();
        }
        else
        {
            sf::sleep(sf::milliseconds(100));
        }
    }
}
```

## Expected behavior
The app should put the sfml logos where I put my fingers.

## Actual behavior
The app crashes sometimes (not always) when touching.<br>
Logcat:
```
10-23 16:51:02.731  9290  9290 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-23 16:51:02.732  9290  9290 F DEBUG   : LineageOS Version: '18.1-20211215-UNOFFICIAL-herolte'
10-23 16:51:02.732  9290  9290 F DEBUG   : Build fingerprint: 'samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU2ERD5:user/release-keys'
10-23 16:51:02.732  9290  9290 F DEBUG   : Revision: '0'
10-23 16:51:02.732  9290  9290 F DEBUG   : ABI: 'arm'
10-23 16:51:02.732  9290  9290 F DEBUG   : Timestamp: 2022-10-23 16:51:02+0200
10-23 16:51:02.732  9290  9290 F DEBUG   : pid: 9242, tid: 9278, name: sfmldev.android  >>> org.sfmldev.android <<<
10-23 16:51:02.733  9290  9290 F DEBUG   : uid: 10225
10-23 16:51:02.733  9290  9290 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
10-23 16:51:02.733  9290  9290 F DEBUG   : Cause: null pointer dereference
10-23 16:51:02.733  9290  9290 F DEBUG   :     r0  be9f19bc  r1  00000008  r2  bd7083a4  r3  00000002
10-23 16:51:02.733  9290  9290 F DEBUG   :     r4  be9f31c0  r5  be9f31c0  r6  be9f31c0  r7  be9f18a8
10-23 16:51:02.733  9290  9290 F DEBUG   :     r8  0000241a  r9  ea418124  r10 be9f31fc  r11 000ff000
10-23 16:51:02.733  9290  9290 F DEBUG   :     ip  ecb4eb14  sp  be9f1878  lr  bf9e7671  pc  bf9e759a
10-23 16:51:02.747  9290  9290 F DEBUG   : backtrace:
10-23 16:51:02.747  9290  9290 F DEBUG   :       #00 pc 0002259a  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-window-d.so (sf::priv::InputImpl::getTouchPosition(unsigned int)+86) (BuildId: 7f6f3fb677c33802200b17862777a0231594efb3)
10-23 16:51:02.747  9290  9290 F DEBUG   :       #01 pc 000225ff  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-window-d.so (sf::priv::InputImpl::getTouchPosition(unsigned int, sf::WindowBase const&)+12) (BuildId: 7f6f3fb677c33802200b17862777a0231594efb3)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #02 pc 000165af  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-window-d.so (sf::Touch::getPosition(unsigned int, sf::WindowBase const&)+14) (BuildId: 7f6f3fb677c33802200b17862777a0231594efb3)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #03 pc 00042769  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-example.so (main+1172) (BuildId: 95d9ca8791e2bc1acbfe46ef08af2b1ceb9a4b47)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #04 pc 00043b23  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-example.so (sf::priv::main(sf::priv::ActivityStates*)+46) (BuildId: 95d9ca8791e2bc1acbfe46ef08af2b1ceb9a4b47)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #05 pc 00046785  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-example.so (decltype(std::__ndk1::forward<void* (*)(sf::priv::ActivityStates*)>(fp)(std::__ndk1::forward<sf::priv::ActivityStates*>(fp0))) std::__ndk1::__invoke<void* (*)(sf::priv::ActivityStates*), sf::priv::ActivityStates*>(void* (*&&)(sf::priv::ActivityStates*), sf::priv::ActivityStates*&&)+30) (BuildId: 95d9ca8791e2bc1acbfe46ef08af2b1ceb9a4b47)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #06 pc 00046723  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-example.so (void std::__ndk1::__thread_execute<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void* (*)(sf::priv::ActivityStates*), sf::priv::ActivityStates*, 2u>(std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void* (*)(sf::priv::ActivityStates*), sf::priv::ActivityStates*>&, std::__ndk1::__tuple_indices<2u>)+34) (BuildId: 95d9ca8791e2bc1acbfe46ef08af2b1ceb9a4b47)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #07 pc 00046331  /data/app/~~qMsv1i2HHKJnk6iv1wYihw==/org.sfmldev.android-GMpnQ_GR1O7oacTU5dsZ7w==/lib/arm/libsfml-example.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void* (*)(sf::priv::ActivityStates*), sf::priv::ActivityStates*> >(void*)+76) (BuildId: 95d9ca8791e2bc1acbfe46ef08af2b1ceb9a4b47)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #08 pc 0008177f  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+40) (BuildId: 4719f38064de5954878af7a6676cb609)
10-23 16:51:02.748  9290  9290 F DEBUG   :       #09 pc 00039da5  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 4719f38064de5954878af7a6676cb609)
```
the crash seems to happen in `SFML/Window/Android/InputImpl.cpp` in `getTouchPosition`, the cause is that it's trying to get the position of a finger that isn't down. But as demonstrated with the above program, checking for that doesn't seem to work reliably.
```cpp
Vector2i InputImpl::getTouchPosition(unsigned int finger)
{
    ALooper_pollAll(0, NULL, NULL, NULL);

    priv::ActivityStates* states = priv::getActivity(NULL);
    Lock lock(states->mutex);

    return states->touchEvents.find(finger)->second;
}
```

### PR DESCRIPTION
**Pull request by JonnyPtn**
Fixes #2257

The issue was easily reproduced with any code that looks something like:

```
for(int i(0); i < 16; ++i)
{
    if (sf::Touch::isDown(i))
    {
         sf::Touch::getPosition(i);
     }
}
```

The issue is both of those functions pump the event queue, so if the finger is released between them (which can happen often if this code is used as part of the main input loop) then the finger is no longer present in the `touchEvents` map so it crashes

It seems like this was part of the initial implementation from 2014: https://github.com/SFML/SFML/commit/fbd21962f099c68f9172a1f5b652ac135cf38df3 and it's not exactly clear why. My best guess would be to try and ensure the check is up to date at all times, but I think in cases like this where our "realtime" checks are really just using cached event data, it's reasonable for them to only be accurate as of the last time the user polled events.

This ensures consistent behaviour - if you check a touch is down, you will get a position. It also matches iOS behaviour and returns (-1,-1) if you request the position without checking if it's down

### CODE REVIEW

**Comment by JonnyPtn** [comment]
After some thought and discussion, I believe we should deprecate these "realtime" touch functions as they aren't actually realtime. The only existing implementations (iOS and Android) use cached event data, as does the open PR for windows support. The linux PR hasn't implemented these API's

Latest change also matches the iOS behaviour when you request the position of a touch that isn't down (returning (-1,-1))

File: examples/tennis/Tennis.cpp [hunk 1]
```diff
@@ -173,13 +173,6 @@ int main()
                 leftPaddle.move({0.f, paddleSpeed * deltaTime});
             }
 
-            if (sf::Touch::isDown(0))
-            {
-                const sf::Vector2i pos       = sf::Touch::getPosition(0);
-                const sf::Vector2f mappedPos = window.mapPixelToCoords(pos);
-                leftPaddle.setPosition({leftPaddle.getPosition().x, mappedPos.y});
-            }
```
Comment (JonnyPtn) [inline examples/tennis/Tennis.cpp:181]: This will mean touch input won't move the paddle on this example - I'd like to implement proper touch support for all examples at some point so have just left it out for now, but could add a new touch implementation using events for this PR if needed

File: examples/opengl/OpenGL.cpp [hunk 2]
```diff
@@ -299,11 +299,7 @@ int main()
             // We get the position of the mouse cursor (or touch), so that we can move the box accordingly
             sf::Vector2i pos;
 
-#ifdef SFML_SYSTEM_IOS
-            pos = sf::Touch::getPosition(0);
```
Comment (JonnyPtn) [inline examples/opengl/OpenGL.cpp:303]: This wasn't working anyway, as it would return -1,-1 when the finger wasn't down so it's off screen. Also doesn't appear to render the cube correctly anyway, just some odd rendering artifacts - A problem for another day I think

File: examples/tennis/Tennis.cpp (hunk 1 above)
Comment (eXpl0it3r) [reply examples/tennis/Tennis.cpp:181]: I think it's fine to remove it for now. Would be great to add touch support later however.

**Comment by eXpl0it3r** [comment]
SFMLBuildMaster: Build this please.

**Comment by eXpl0it3r** [comment]
See also the following comment for the reasoning behind the depreciation: https://github.com/SFML/SFML/issues/2257#issuecomment-3777084144
