### PR TITLE
Fixed modifiers causing sf::Keyboard::Unknown being returned

### LINKED ISSUE #1012: Only lowercase keypresses are handled on Linux
In [WindowImplX11.cpp](https://github.com/SFML/SFML/blob/master/src/SFML/Window/Unix/WindowImplX11.cpp) function "*keysymToSF(xcb_keysym_t symbol)*" handles only lowercase KeySym's(XK_a, XK_b, e.t.c.). 
This causes SFML to generate sf::Keyboard::Unknown keycodes in button events when CapsLock and/or L/RShift is pressed.
As of [Xlib manual](https://tronche.com/gui/x/xlib/input/keyboard-encoding.html#KeySym) uppercase presses are generated too and they should be handled as XK_A, XK_B, e.t.c.

I'm running Linux 3.19.0-33-generic Ubuntu-14.04.1 i686

### PR DESCRIPTION
**Pull request by binary1248**
Fixes #1012.

### CODE REVIEW

**Comment by eXpl0it3r** [comment]
Can someone else on Linux test this as well?

**Comment by binary1248** [comment]
Bump.

File: src/SFML/Window/Unix/WindowImplX11.cpp [hunk 1]
```diff
@@ -1757,17 +1757,23 @@ bool WindowImplX11::processEvent(XEvent windowEvent)
...
         {
-            // Get the keysym of the key that has been pressed
-            static XComposeStatus keyboard;
-            char buffer[32];
-            KeySym symbol;
-            XLookupString(&windowEvent.xkey, buffer, sizeof(buffer), &symbol, &keyboard);
+            Keyboard::Key key = Keyboard::Unknown;
+
+            // Try each KeySym index (modifier group) until we get a match
+            for (int i = 0; i < 4; ++i)
```
Comment (TankOs) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: Where does the 4 (or 0-3) come from? I looked up `XLookupKeysym()` but as always, X11 documentation is a pain in the *ss.

**Comment by TankOs** [comment]
Works for me: :+1: I added another patch on top of this to fix RAlt detection. Might want to merge: [bugfix/unix_keyevents_ralt](https://github.com/SFML/SFML/tree/bugfix/unix_keyevents_ralt)

File: src/SFML/Window/Unix/WindowImplX11.cpp (hunk 1 above)
Comment (binary1248) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: There are up to 4 modifier groups per cap, e.g. on [this layout](https://upload.wikimedia.org/wikipedia/commons/2/22/KB_US-International.svg). One for each symbol in the 4 corners of a cap. The API probably doesn't state a maximum value for this because there might be keyboards with even more. :grin:

**Comment by binary1248** [comment]
I already considered this in #922, but came to the conclusion that this is a user configuration option.

File: src/SFML/Window/Unix/WindowImplX11.cpp (hunk 1 above)
Comment (TankOs) [inline src/SFML/Window/Unix/WindowImplX11.cpp]: I see, so on Linux, this can basically be Shift, Control, Super, Meta, Hyper, Mod1, Mod2, Mod3, Mod4, Mod5. :P Thanks for clarification.

**Comment by TankOs** [comment]
It's indeed a configuration option, but we should really go with the defaults here. I asked several people on IRC to show their `xmodmap` output, and it has been consistent with this:

```
% xmodmap 
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

Alt_R is never mapped, so that key doesn't work at all. Asking the user to configure X.Org just to have a working AltGr key is ridiculous.

**Comment by binary1248** [comment]
My `xmodmap` output looks like this:
```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

Like I said, this depends on the user's mapping. Using English mappings will also map Alt_R because the key isn't used as a modifier. Because AltGr is a key modifier on e.g. German mappings and is used to shift keysyms, it isn't mapped on those, with reason. Switching between mappings will also add/remove the Alt_R mapping depending on the target layout. If a user really wanted to use a key that is intended to be used as a keysym shift as a "normal" non-modifier key, they would be better off configuring it to behave as such. This keeps SFML consistent with other libraries who also decided that handling Alt_R is up to the user if they have more than 1 option. Applications that aim to be "international friendly" should not endorse use of Alt_R anyway.

**Comment by TankOs** [comment]
US keyboards don't have AltGr, but they still have an Alt key there, which is also mapped by SFML, to `sf::Keyboard::Key::RAlt`. On my system, it's mapped to `::Unknown`, because in the same place I have AltGr, which is not mapped by SFML.

The simple question is: Why is `Alt_R` mapped, but `ISO_Shift_Level_3` and `Mode_Switch` are not? All 3 symbols are triggered by the same key on the proper keyboard layouts. Even if AltGr acts as a modifier key on non-US layouts, what's the problem? Shift, Control and (L)Alt are also modifier keys, yet we map them (for good reasons).

**Comment by binary1248** [comment]
Simple... because Shift, Control and LAlt are also present on all keyboards. If SFML were designed from the beginning to be e.g. German-centric, I could imagine there also being an `sf::Keyboard::Key::Oe` and `sf::Keyboard::Key::Ae` or similar keys, because those have to be made accessible to people who want to check for those keystrokes. However, besides being of use to people who use German keyboards (or other keyboards where they are present) they are pretty useless. If you are using a German keyboard, there is no direct, single keystroke way of triggering a e.g. sf::Keyboard::Key::LBracket keystroke either, because there is no unmodified way to get this.

The reason why you don't get RAlt using a German layout is well.... because Germans don't have an RAlt key. :stuck_out_tongue: They have an AltGr key, and that is not the same as RAlt even though some might consider it as such (if it would have been named something completely different like "Right Shift" or something there would probably be less confusion). That is one of the disadvantages of having an English-centric API, but like I said, other libraries don't do much different either.

**Comment by TankOs** [comment]
Ä/Ö/Ü etc. are mapped to their US counterparts. The implementation is not ideal, because there are indeed many differences (this is also what's being discussed...more or less ;)), but at least I can **detect key presses**.

While there's no Key::Ue, I can still check for the English counterpart, and that's good enough. I can just get an image of the default US layout and can work with that. There's one key that I can't simply map, and that's less-than, because on the US keyboard they have a larger shift key there.

However, the point is: I can use the keys. But I can't use AltGr, it's completely dead. And that makes no sense, because it's at the exact same location as on the US keyboard, just without "Gr". I really don't see a practical reason why this can't/shouldn't be supported. Not being able to map keys makes me go crazy when it's technically possible, even without a keyboard layout rewrite in SFML.

**Comment by binary1248** [comment]
I personally don't really mind if AltGr gets mapped or not, the only reason as I already mentioned why I closed my initial PR was because it diverted from what other libraries did. If consistency with other libraries in this regard is not a concern I don't have anything against your change.

@TankOs Feel free to open a PR for bugfix/unix_keyevents_ralt and/or feature/more_keys and close this PR as superseded.

**Comment by eXpl0it3r** [comment]
So is this PR obsolete (once @TankOs implements the other bits)?

**Comment by binary1248** [comment]
Yes.

**Comment by binary1248** [comment]
Until the Windows and OS X implementations for #1045 are ready, this will have to take its place in order to fix #1012 for 2.4. #1045 will be rebased onto master in 2.5.

**Comment by eXpl0it3r** [comment]
This PR has been added to my merge list, meaning it will be merged soon, unless someone raises any concerns.
